// release-feedback-scan/linear-client.js
// Linear API calls — create Feedback Summary issue, write attachments, post artifact comment.
// Uses Linear REST API with a personal API token stored as an env var.

const LINEAR_API = "https://api.linear.app/graphql";
const HEADERS = {
  "Authorization": process.env.LINEAR_API_TOKEN,
  "Content-Type": "application/json",
};

async function linearFetch(query, variables = {}) {
  const res = await fetch(LINEAR_API, {
    method: "POST",
    headers: HEADERS,
    body: JSON.stringify({ query, variables }),
  });
  const json = await res.json();
  if (json.errors) throw new Error(`Linear API error: ${JSON.stringify(json.errors)}`);
  return json.data;
}

/**
 * Create a Feedback Summary issue inside a Linear project.
 * @param {string} projectId  — Linear project ID
 * @param {string} releaseTitle
 * @param {object[]} tickets  — matched ZD tickets
 * @returns {Promise<{id: string, url: string}>}
 */
async function createFeedbackSummaryIssue(projectId, releaseTitle, tickets) {
  const query = `
    mutation CreateIssue($input: IssueCreateInput!) {
      issueCreate(input: $input) {
        issue { id url }
      }
    }
  `;
  const data = await linearFetch(query, {
    input: {
      title: `Feedback Summary — ${releaseTitle}`,
      description: `Auto-created by Aether. ${tickets.length} Zendesk ticket(s) matched this release.`,
      projectId,
      labelIds: [], // add "feedback" label ID here once confirmed with Brady
    }
  });
  return data.issueCreate.issue;
}

/**
 * Write ZD ticket attachments to a Linear issue.
 * @param {string} issueId
 * @param {object[]} tickets
 */
async function writeAttachments(issueId, tickets) {
  const query = `
    mutation CreateAttachment($input: AttachmentCreateInput!) {
      attachmentCreate(input: $input) {
        attachment { id }
      }
    }
  `;
  for (const ticket of tickets) {
    await linearFetch(query, {
      input: {
        issueId,
        title: `ZD-${ticket.id} · ${ticket.via?.source?.from?.name ?? "Customer"} · "${ticket.subject}"`,
        url: `https://7shifts.zendesk.com/agent/tickets/${ticket.id}`,
      }
    });
  }
}

/**
 * Post artifact comment to a Linear issue with ticket count + top themes.
 * @param {string} issueId
 * @param {object[]} tickets
 * @param {string[]} keywords
 */
async function postArtifactComment(issueId, tickets, keywords) {
  const query = `
    mutation CreateComment($input: CommentCreateInput!) {
      commentCreate(input: $input) {
        comment { id }
      }
    }
  `;
  const body = [
    `**🤖 Aether Feedback Summary**`,
    ``,
    `**Tickets matched:** ${tickets.length}`,
    `**Top keywords:** ${keywords.slice(0, 5).join(", ")}`,
    `**Companies:** ${[...new Set(tickets.map(t => t.organization?.name).filter(Boolean))].slice(0, 5).join(", ") || "—"}`,
    ``,
    `_Generated by Aether feedback-scan. Confidence thresholds: ≥0.80 auto-tag, 0.60–0.79 needs-review._`,
  ].join("\n");

  await linearFetch(query, { input: { issueId, body } });
}

module.exports = { createFeedbackSummaryIssue, writeAttachments, postArtifactComment };
