// release-feedback-scan/linear-client.js
// Linear API calls — create Feedback Summary issue, write attachments, post artifact comment.
// Uses Linear GraphQL API with a service account API token stored as an env var.
//
// NOTE: LINEAR_API_TOKEN must be a SERVICE ACCOUNT token, not a personal token.
// Personal tokens break if the owner leaves or revokes access.
// Brady to provision a dedicated Aether service account in Linear.

const LINEAR_API = "https://api.linear.app/graphql";

function getHeaders() {
  return {
    "Authorization": process.env.LINEAR_API_TOKEN,
    "Content-Type": "application/json",
  };
}

async function linearFetch(query, variables = {}) {
  const res = await fetch(LINEAR_API, {
    method: "POST",
    headers: getHeaders(),
    body: JSON.stringify({ query, variables }),
  });
  const json = await res.json();
  if (json.errors) throw new Error(`Linear API error: ${JSON.stringify(json.errors)}`);
  return json.data;
}

/**
 * Resolve a Linear project identifier (e.g. "ENG-123") to its internal UUID.
 * The Linear native trigger payload provides the identifier, but mutations
 * require the UUID. This lookup bridges the gap.
 *
 * NOTE FOR BRADY: Confirm what exact fields the Linear native trigger sends
 * in its payload. If it already sends the UUID as `project.id`, this function
 * is not needed and createFeedbackSummaryIssue can use the ID directly.
 *
 * @param {string} identifier — e.g. "ENG-123" or raw UUID (detected automatically)
 * @returns {Promise<string>} — UUID
 */
async function resolveProjectId(identifier) {
  // If it's already a UUID, return as-is
  if (/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(identifier)) {
    return identifier;
  }

  // Otherwise look up the project by slug/identifier
  const query = `
    query ResolveProject($slugId: String!) {
      project(id: $slugId) {
        id
        name
      }
    }
  `;
  const data = await linearFetch(query, { slugId: identifier });
  if (!data.project) throw new Error(`Linear project not found for identifier: ${identifier}`);
  return data.project.id;
}

/**
 * Create a Feedback Summary issue inside a Linear project.
 * @param {string} projectIdentifier — Linear project identifier OR UUID
 * @param {string} releaseTitle
 * @param {object[]} tickets  — matched ZD tickets
 * @returns {Promise<{id: string, url: string}>}
 */
async function createFeedbackSummaryIssue(projectIdentifier, releaseTitle, tickets) {
  // Resolve identifier → UUID before mutation
  const projectId = await resolveProjectId(projectIdentifier);

  const query = `
    mutation CreateIssue($input: IssueCreateInput!) {
      issueCreate(input: $input) {
        issue { id url }
      }
    }
  `;
  const data = await linearFetch(query, {
    input: {
      title: `Feedback Summary — ${releaseTitle}`,
      description: `Auto-created by Aether. ${tickets.length} Zendesk ticket(s) matched this release.`,
      projectId,
      labelIds: [], // TODO: add "feedback" label ID once confirmed with Brady
    }
  });
  return data.issueCreate.issue;
}

/**
 * Write ZD ticket attachments to a Linear issue.
 * Per-attachment errors are caught and logged — does not abort on failure.
 * @param {string} issueId
 * @param {object[]} tickets
 */
async function writeAttachments(issueId, tickets) {
  const query = `
    mutation CreateAttachment($input: AttachmentCreateInput!) {
      attachmentCreate(input: $input) {
        attachment { id }
      }
    }
  `;
  for (const ticket of tickets) {
    try {
      await linearFetch(query, {
        input: {
          issueId,
          title: `ZD-${ticket.id} · ${ticket.via?.source?.from?.name ?? "Customer"} · "${ticket.subject}"`,
          url: `https://7shifts.zendesk.com/agent/tickets/${ticket.id}`,
        }
      });
    } catch (err) {
      console.error(`[linear-client] Failed to write attachment for ZD-${ticket.id}: ${err.message}`);
    }
  }
}

/**
 * Post artifact comment to a Linear issue with ticket count + top themes.
 * @param {string} issueId
 * @param {object[]} tickets
 * @param {string[]} keywords
 */
async function postArtifactComment(issueId, tickets, keywords) {
  const query = `
    mutation CreateComment($input: CommentCreateInput!) {
      commentCreate(input: $input) {
        comment { id }
      }
    }
  `;
  const body = [
    `**🤖 Aether Feedback Summary**`,
    ``,
    `**Tickets matched:** ${tickets.length}`,
    `**Top keywords:** ${keywords.slice(0, 5).join(", ")}`,
    `**Companies:** ${[...new Set(tickets.map(t => t.organization?.name).filter(Boolean))].slice(0, 5).join(", ") || "—"}`,
    ``,
    `_Generated by Aether feedback-scan. Confidence thresholds: ≥0.80 auto-tag, 0.60–0.79 needs-review._`,
  ].join("\n");

  await linearFetch(query, { input: { issueId, body } });
}

module.exports = {
  resolveProjectId,
  createFeedbackSummaryIssue,
  writeAttachments,
  postArtifactComment,
};
